### ISSUE TITLE
Paged for 5xx error rates > 1% 2015-12-13T03:26:00

### ISSUE THREAD

**Issue by jbuck** [mozilla/donate.mozilla.org#1099]

**Comment by jbuck** [comment]
I see one 500 error in the heroku metrics

**Comment by jbuck** [comment]
I think this might be a Hapi bug. I see a lots of requests like:

```
 » 12 Dec 2015 22:25:51.342 2015-12-13 03:25:51.278414+00:00 heroku router - - at=info method=HEAD path="/����%20wwwroot.rar" host=donate-mozilla-org-us-prod.herokuapp.com request_id=bd1395f9-21b7-410f-a1d7-21c1009c03c0 fwd="112.11.81.35,54.239.129.197" dyno=web.1 connect=0ms service=18ms status=500 bytes=333 
 » 12 Dec 2015 22:25:51.571 2015-12-13 03:25:51.269736+00:00 app web.1 - - message="Uncaught error: Header value cannot contain or convert into non-ascii characters: location" stack="Error: Uncaught error: Header value cannot contain or convert into non-ascii characters: location at Object.exports.contain.exports.reachTemplate.exports.assert (/app/node_modules/hapi/node_modules/hoek/lib/index.js:730:11) at internals.Response._header (/app/node_modules/hapi/lib/response.js:132:22) at internals.Response.location (/app/node_modules/hapi/lib/response.js:208:10) at internals.Response.redirect (/app/node_modules/hapi/lib/response.js:257:10) at Function.internals.Reply.interface.internals.redirect (/app/node_modules/hapi/lib/reply.js:126:30) at /app/server.js:225:20 at /app/node_modules/hapi/lib/request.js:397:22 at iterate (/app/node_modules/hapi/node_modules/items/lib/index.js:36:13) at Object.exports.serial (/app/node_modules/hapi/node_modules/items/lib/index.js:39:9) at /app/node_modules/hapi/lib/request.js:392:15 at internals.Protect.run.finish [as run] (/app/node_modules/hapi/lib/protect.js:64:5) at internals.Request.internals.Request._execute.internals.Request._lifecycle.internals.Request._invoke.callback._protect.run [as _invoke] (/app/node_modules/hapi/lib/request.js:390:19) at internals.Request.internals.Request._execute.internals.Request._lifecycle.internals.Request._invoke.internals.Request._reply.exit [as _reply] (/app/node_modules/hapi/lib/request.js:449:10) at /app/node_modules/hapi/lib/request.js:383:21 at done (/app/node_modules/hapi/node_modules/items/lib/index.js:31:25) at finalize (/app/node_modules/hapi/lib/handler.js:21:16)" tags=error timestring=2015-12-13T03:25:51.256Z Exception 
 » 12 Dec 2015 22:25:51.573 2015-12-13 03:25:51.279724+00:00 app web.1 - - Debug: internal, implementation, error 
 » 12 Dec 2015 22:25:51.573 2015-12-13 03:25:51.279727+00:00 app web.1 - - Error: Uncaught error: Header value cannot contain or convert into non-ascii characters: location at Object.exports.contain.exports.reachTemplate.exports.assert (/app/node_modules/hapi/node_modules/hoek/lib/index.js:730:11) at internals.Response._header (/app/node_modules/hapi/lib/response.js:132:22) at internals.Response.location (/app/node_modules/hapi/lib/response.js:208:10) at internals.Response.redirect (/app/node_modules/hapi/lib/response.js:257:10) at Function.internals.Reply.interface.internals.redirect (/app/node_modules/hapi/lib/reply.js:126:30) at /app/server.js:225:20 at /app/node_modules/hapi/lib/request.js:397:22 at iterate (/app/node_modules/hapi/node_modules/items/lib/index.js:36:13) at Object.exports.serial (/app/node_modules/hapi/node_modules/items/lib/index.js:39:9) at /app/node_modules/hapi/lib/request.js:392:15 at internals.Protect.run.finish [as run] (/app/node_modules/hapi/lib/protect.js:64:5) at internals.Request.internals.Request._execute.internals.Request._lifecycle.internals.Request._invoke.callback._protect.run [as _invoke] (/app/node_modules/hapi/lib/request.js:390:19) at internals.Request.internals.Request._execute.internals.Request._lifecycle.internals.Request._invoke.internals.Request._reply.exit [as _reply] (/app/node_modules/hapi/lib/request.js:449:10) at /app/node_modules/hapi/lib/request.js:383:21 at done (/app/node_modules/hapi/node_modules/items/lib/index.js:31:25) at finalize (/app/node_modules/hapi/lib/handler.js:21:16) Exception 
 » 12 Dec 2015 22:25:53.929 2015-12-13 03:25:53.773687+00:00 heroku router - - at=info method=HEAD path="/����%20www.zip" host=donate-mozilla-org-us-prod.herokuapp.com request_id=ae35a952-7c69-4f62-9058-dc58bfa3a463 fwd="112.11.81.35,54.239.129.11" dyno=web.2 connect=0ms service=63ms status=500 bytes=333 
 » 12 Dec 2015 22:25:54.068 2015-12-13 03:25:53.761670+00:00 app web.2 - - message="Uncaught error: Header value cannot contain or convert into non-ascii characters: location" stack="Error: Uncaught error: Header value cannot contain or convert into non-ascii characters: location at Object.exports.contain.exports.reachTemplate.exports.assert (/app/node_modules/hapi/node_modules/hoek/lib/index.js:730:11) at internals.Response._header (/app/node_modules/hapi/lib/response.js:132:22) at internals.Response.location (/app/node_modules/hapi/lib/response.js:208:10) at internals.Response.redirect (/app/node_modules/hapi/lib/response.js:257:10) at Function.internals.Reply.interface.internals.redirect (/app/node_modules/hapi/lib/reply.js:126:30) at /app/server.js:225:20 at /app/node_modules/hapi/lib/request.js:397:22 at iterate (/app/node_modules/hapi/node_modules/items/lib/index.js:36:13) at Object.exports.serial (/app/node_modules/hapi/node_modules/items/lib/index.js:39:9) at /app/node_modules/hapi/lib/request.js:392:15 at internals.Protect.run.finish [as run] (/app/node_modules/hapi/lib/protect.js:64:5) at internals.Request.internals.Request._execute.internals.Request._lifecycle.internals.Request._invoke.callback._protect.run [as _invoke] (/app/node_modules/hapi/lib/request.js:390:19) at internals.Request.internals.Request._execute.internals.Request._lifecycle.internals.Request._invoke.internals.Request._reply.exit [as _reply] (/app/node_modules/hapi/lib/request.js:449:10) at /app/node_modules/hapi/lib/request.js:383:21 at done (/app/node_modules/hapi/node_modules/items/lib/index.js:31:25) at finalize (/app/node_modules/hapi/lib/handler.js:21:16)" tags=error timestring=2015-12-13T03:25:53.697Z Exception 
 » 12 Dec 2015 22:25:54.071 2015-12-13 03:25:53.762319+00:00 app web.2 - - Debug: internal, implementation, error 
```

**Comment by jbuck** [comment]
https://logentries.com/app/08cedfce#/log/7dd843ae-5b0d-3963-b7aa-07473ab07241/?log_q=&f=1449977035000&t=1449977280000

**Comment by jbuck** [comment]
I think I'll try to get down the exact path used by this scrub and file an upstream bug with Hapi, since it shouldn't be throwing an error here.

**Comment by alicoding** [comment]
My understanding based on the context of the issue here is that this is not someone trying to donate and failed but looks like someone found a bug on Hapi and trying to crash the server or something?

**Comment by jbuck** [comment]
@alicoding Yeah, that sounds reasonable

**Comment by jbuck** [comment]
I looked at the Hapi code, and I think we can solve this with a regex that strips out non-ASCII characters.
