### ISSUE TITLE
Uncaught error: Cannot read property 'zeroDecimal' of undefined

### ISSUE THREAD

**Issue by alicoding** [mozilla/donate.mozilla.org#1101]
```
 » 13 Dec 2015 16:55:59.759 2015-12-13 21:55:59.451045+00:00 app web.1 - - message="Uncaught error: Cannot read property 'zeroDecimal' of undefined" stack="TypeError: Uncaught error: Cannot read property 'zeroDecimal' of undefined at Object.amountModifier.modify (/app/scripts/amount-modifier.js:20:31) at Object.amountModifier.paypal (/app/scripts/amount-modifier.js:36:17) at routes.paypal (/app/routes/index.js:165:33) at Object.exports.execute.internals.prerequisites.internals.handler.callback [as handler] (/app/node_modules/hapi/lib/handler.js:96:36) at /app/node_modules/hapi/lib/handler.js:30:23 at internals.Protect.run.finish [as run] (/app/node_modules/hapi/lib/protect.js:64:5) at exports.execute.finalize (/app/node_modules/hapi/lib/handler.js:24:22) at each (/app/node_modules/hapi/lib/request.js:378:16) at iterate (/app/node_modules/hapi/node_modules/items/lib/index.js:36:13) at done (/app/node_modules/hapi/node_modules/items/lib/index.js:28:25) at request._protect.run (/app/node_modules/hapi/lib/validation.js:59:20) at internals.Any.applyFunctionToChildren.internals.Any._validateWithOptions (/app/node_modules/hapi/node_modules/joi/lib/any.js:657:16) at root.validate (/app/node_modules/hapi/node_modules/joi/lib/index.js:102:23) at Object.internals.input.postValidate [as input] (/app/node_modules/hapi/lib/validation.js:131:20) at exports.payload (/app/node_modules/hapi/lib/validation.js:29:22) at each (/app/node_modules/hapi/lib/request.js:378:16)" tags=error timestring=2015-12-13T21:55:59.443Z Exception Context 
```

There are 6 of them in logentries.

**Comment by alicoding** [comment]
```
 » 13 Dec 2015 16:55:59.764 2015-12-13 21:55:59.452269+00:00 app web.1 - - Debug: internal, implementation, error
» 13 Dec 2015 16:55:59.764 2015-12-13 21:55:59.452272+00:00 app web.1 - - TypeError: Uncaught error: Cannot read property 'zeroDecimal' of undefined at Object.amountModifier.modify (/app/scripts/amount-modifier.js:20:31) at Object.amountModifier.paypal (/app/scripts/amount-modifier.js:36:17) at routes.paypal (/app/routes/index.js:165:33) at Object.exports.execute.internals.prerequisites.internals.handler.callback [as handler] (/app/node_modules/hapi/lib/handler.js:96:36) at /app/node_modules/hapi/lib/handler.js:30:23 at internals.Protect.run.finish [as run] (/app/node_modules/hapi/lib/protect.js:64:5) at exports.execute.finalize (/app/node_modules/hapi/lib/handler.js:24:22) at each (/app/node_modules/hapi/lib/request.js:378:16) at iterate (/app/node_modules/hapi/node_modules/items/lib/index.js:36:13) at done (/app/node_modules/hapi/node_modules/items/lib/index.js:28:25) at request._protect.run (/app/node_modules/hapi/lib/validation.js:59:20) at internals.Any.applyFunctionToChildren.internals.Any._validateWithOptions (/app/node_modules/hapi/node_modules/joi/lib/any.js:657:16) at root.validate (/app/node_modules/hapi/node_modules/joi/lib/index.js:102:23) at Object.internals.input.postValidate [as input] (/app/node_modules/hapi/lib/validation.js:131:20) at exports.payload (/app/node_modules/hapi/lib/validation.js:29:22) at each (/app/node_modules/hapi/lib/request.js:378:16) Exception
» 13 Dec 2015 16:55:59.782 2015-12-13 21:55:59.492296+00:00 app web.2 - - message="Uncaught error: Cannot read property 'zeroDecimal' of undefined" stack="TypeError: Uncaught error: Cannot read property 'zeroDecimal' of undefined at Object.amountModifier.modify (/app/scripts/amount-modifier.js:20:31) at Object.amountModifier.paypal (/app/scripts/amount-modifier.js:36:17) at routes.paypal (/app/routes/index.js:165:33) at Object.exports.execute.internals.prerequisites.internals.handler.callback [as handler] (/app/node_modules/hapi/lib/handler.js:96:36) at /app/node_modules/hapi/lib/handler.js:30:23 at internals.Protect.run.finish [as run] (/app/node_modules/hapi/lib/protect.js:64:5) at exports.execute.finalize (/app/node_modules/hapi/lib/handler.js:24:22) at each (/app/node_modules/hapi/lib/request.js:378:16) at iterate (/app/node_modules/hapi/node_modules/items/lib/index.js:36:13) at done (/app/node_modules/hapi/node_modules/items/lib/index.js:28:25) at request._protect.run (/app/node_modules/hapi/lib/validation.js:59:20) at internals.Any.applyFunctionToChildren.internals.Any._validateWithOptions (/app/node_modules/hapi/node_modules/joi/lib/any.js:657:16) at root.validate (/app/node_modules/hapi/node_modules/joi/lib/index.js:102:23) at Object.internals.input.postValidate [as input] (/app/node_modules/hapi/lib/validation.js:131:20) at exports.payload (/app/node_modules/hapi/lib/validation.js:29:22) at each (/app/node_modules/hapi/lib/request.js:378:16)" tags=error timestring=2015-12-13T21:55:59.482Z Exception
```

**Comment by jbuck** [comment]
@alicoding Is this the error messages that you got paged for this morning?

**Comment by ScottDowne** [comment]
Look at those logs, I also saw a few minutes later 400-ish stripe requests in 5 or so minutes:
![stripe-wtf](https://cloud.githubusercontent.com/assets/197334/11785734/2b548336-a251-11e5-946f-383c0e5b6625.png)

Someone hitting up our endpoint directly? If they did that with undefined currency, they would receive the error @alicoding is seeing.

**Comment by alicoding** [comment]
@jbuck I didn't get page for these errors actually.

**Comment by jbuck** [comment]
This was someone sending a currency that we don't support. We'll fix this by testing for valid currencies in the route validation.
