### ISSUE TITLE
Unable to build/run server on Windows 10

### ISSUE THREAD

**Issue by cadecairos** [mozilla/donate.mozilla.org#1635]
I get this error running `npm server` in PowerShell:

```
ERROR in ./less/index.less
Module build failed: Error: ENOTSUP: operation not supported on socket, uv_interface_addresses
    at Error (native)
    at Object.lib.networkInterfaces (/mnt/c/Users/cade/projects/donate.mozilla.org/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-filter-plugins/node_modules/uniqid/node_modules/macaddress/index.js:31:21)
    at Object.lib.one (/mnt/c/Users/cade/projects/donate.mozilla.org/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-filter-plugins/node_modules/uniqid/node_modules/macaddress/index.js:79:26)
    at Object.<anonymous> (/mnt/c/Users/cade/projects/donate.mozilla.org/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-filter-plugins/node_modules/uniqid/index.js:15:77)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/mnt/c/Users/cade/projects/donate.mozilla.org/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-filter-plugins/dist/index.js:9:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/mnt/c/Users/cade/projects/donate.mozilla.org/node_modules/css-loader/node_modules/cssnano/dist/index.js:21:30)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/mnt/c/Users/cade/projects/donate.mozilla.org/node_modules/css-loader/lib/processCss.js:15:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
 @ multi main
Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in ENOTSUP: operation not supported on socket, uv_interface_addresses
```

**Comment by cadecairos** [comment]
I don't have this issue anymore, I think it was a problem on my end.
