### ISSUE TITLE
Uncaught exception if location header contains non-ascii characters

### ISSUE THREAD

**Issue by cadecairos** [mozilla/donate.mozilla.org#1698]
Somebody is trying to actively scan donate.mozilla.org for security bugs, and I noticed that their scanner triggered this error:

```
Uncaught error: Header value cannot contain or convert into non-ascii characters: location" stack="Error: Uncaught error: Header value cannot contain or convert into non-ascii characters: location
» 13 Dec 2016 08:58:19.963 191 <190>1 2016-12-13T13:58:19.600315+00:00 host app web.1 -     at Object.exports.contain.exports.reachTemplate.exports.assert.condition [as assert] (/app/node_modules/hoek/lib/index.js:732:11)
» 13 Dec 2016 08:58:19.963 139 <190>1 2016-12-13T13:58:19.600317+00:00 host app web.1 -     at internals.Response._header (/app/node_modules/hapi/lib/response.js:141:22)
» 13 Dec 2016 08:58:19.963 140 <190>1 2016-12-13T13:58:19.600317+00:00 host app web.1 -     at internals.Response.location (/app/node_modules/hapi/lib/response.js:217:10)
» 13 Dec 2016 08:58:19.963 140 <190>1 2016-12-13T13:58:19.600318+00:00 host app web.1 -     at internals.Response.redirect (/app/node_modules/hapi/lib/response.js:266:10)
» 13 Dec 2016 08:58:19.963 106 <190>1 2016-12-13T13:58:19.600319+00:00 host app web.1 -     at /app/dist/lib/react-server-route.js:11:35
» 13 Dec 2016 08:58:19.963 113 <190>1 2016-12-13T13:58:19.600320+00:00 host app web.1 -     at /app/node_modules/react-router/lib/match.js:65:5
» 13 Dec 2016 08:58:19.963 132 <190>1 2016-12-13T13:58:19.600321+00:00 host app web.1 -     at /app/node_modules/react-router/lib/createTransitionManager.js:101:9
» 13 Dec 2016 08:58:19.963 126 <190>1 2016-12-13T13:58:19.600321+00:00 host app web.1 -     at next (/app/node_modules/react-router/lib/AsyncUtils.js:48:16)
» 13 Dec 2016 08:58:19.963 137 <190>1 2016-12-13T13:58:19.600322+00:00 host app web.1 -     at Object.loopAsync (/app/node_modules/react-router/lib/AsyncUtils.js:58:3)
» 13 Dec 2016 08:58:19.963 147 <190>1 2016-12-13T13:58:19.600323+00:00 host app web.1 -     at Object.runEnterHooks (/app/node_modules/react-router/lib/TransitionUtils.js:70:15)
» 13 Dec 2016 08:58:19.963 146 <190>1 2016-12-13T13:58:19.600324+00:00 host app web.1 -     at finishMatch (/app/node_modules/react-router/lib/createTransitionManager.js:97:22)
» 13 Dec 2016 08:58:19.963 132 <190>1 2016-12-13T13:58:19.600324+00:00 host app web.1 -     at /app/node_modules/react-router/lib/createTransitionManager.js:78:11
» 13 Dec 2016 08:58:19.963 126 <190>1 2016-12-13T13:58:19.600325+00:00 host app web.1 -     at next (/app/node_modules/react-router/lib/AsyncUtils.js:48:16)
» 13 Dec 2016 08:58:19.963 137 <190>1 2016-12-13T13:58:19.600326+00:00 host app web.1 -     at Object.loopAsync (/app/node_modules/react-router/lib/AsyncUtils.js:58:3)
» 13 Dec 2016 08:58:19.963 121 <190>1 2016-12-13T13:58:19.600326+00:00 host app web.1 -     at /app/node_modules/react-router/lib/matchRoutes.js:193:17
» 13 Dec 2016 08:58:19.963 202 <190>1 2016-12-13T13:58:19.600330+00:00 host app web.1 -     at Object.matchRoutes [as default] (/app/node_modules/react-router/lib/matchRoutes.js:202:5)
```

**Comment by cadecairos** [comment]
This hasn't shown up in a while. wont-fixing.
