### ISSUE TITLE
Traceback on dev setup, on first load

### ISSUE THREAD

**Issue by davidascher** [mozilla/donate.mozilla.org#390]
Trying w/ node 4.0 (this may be part of the problem).

Following directions, I get the site to render fine, but the server barfs with:

```
dascher-29223:donate.mozilla.org dascher1$ npm build
dascher-29223:donate.mozilla.org dascher1$ npm start

> donate.mozilla.org@0.0.1 start /Users/dascher1/davida/src/donate.mozilla.org
> node scripts/build


> donate.mozilla.org@0.0.1 start:dev /Users/dascher1/davida/src/donate.mozilla.org
> npm-run-all --parallel build:l10njson build:exchangerates watch:js server watch:css


> donate.mozilla.org@0.0.1 build:l10njson /Users/dascher1/davida/src/donate.mozilla.org
> node scripts/properties2json


> donate.mozilla.org@0.0.1 build:exchangerates /Users/dascher1/davida/src/donate.mozilla.org
> node scripts/exchangerates.js


> donate.mozilla.org@0.0.1 watch:js /Users/dascher1/davida/src/donate.mozilla.org
> webpack -w


> donate.mozilla.org@0.0.1 server /Users/dascher1/davida/src/donate.mozilla.org
> node start.js


> donate.mozilla.org@0.0.1 watch:css /Users/dascher1/davida/src/donate.mozilla.org
> mkdirp public/css && autoless less public/css --autoprefix '> 1%, last 2 versions'  --source-map

Done writing: /Users/dascher1/davida/src/donate.mozilla.org/locales/en-US.json
Done writing: /Users/dascher1/davida/src/donate.mozilla.org/locales/de.json
Done writing: /Users/dascher1/davida/src/donate.mozilla.org/locales/fr.json
Done writing: /Users/dascher1/davida/src/donate.mozilla.org/locales/pt-BR.json
Done writing: /Users/dascher1/davida/src/donate.mozilla.org/locales/es.json
Done writing: /Users/dascher1/davida/src/donate.mozilla.org/locales/id.json
[exchangerates.js] Finished checking for local copy of exchange rates
[exchangerates.js] Found local copy of exchange rates
[exchangerates.js] Latest exchange rate snapshot is 3542 seconds old. No need to refresh.
Finding files...
o less/shared.less
o less/components/currency-dropdown.less
o less/components/footer.less
o less/components/header.less
o less/components/index.less
o less/components/navigation-button.less
o less/components/navigation-menu.less
o less/components/navigation-page.less
o less/components/next-button.less
o less/components/paypal-button.less
o less/components/simple-paypal.less
o less/components/small-print.less
o less/pages/give-bitcoin.less
o less/pages/index.less
o less/pages/share.less
150910/235912.811, [log,info], data: Running server at: http://localhost:3000
✓ less/index.less -> public/css/index.css
Monitoring files in less
150910/235915.827, [response], http://localhost:3000: get /en-US/ {} 304 (2ms)
150910/235915.954, [response], http://localhost:3000: get /main.js {} 304 (10ms)
150910/235915.954, [response], http://localhost:3000: get /js/stripe.js {} 304 (11ms)
150910/235915.956, [response], http://localhost:3000: get /js/stripe-checkout.js {} 304 (10ms)
150910/235915.957, [response], http://localhost:3000: get /js/ga.js {} 304 (10ms)
150910/235915.951, [response], http://localhost:3000: get /css/index.css {} 200 (18ms)
150910/235916.150, [response], http://localhost:3000: get /images/Mozilla-wordmark.png {} 304 (5ms)
150910/235916.233, [response], http://localhost:3000: get /images/favicon.ico {} 304 (4ms)
150910/235916.251, [response], http://localhost:3000: get /images/payment_logos_updated.png {} 304 (2ms)
/Users/dascher1/davida/src/donate.mozilla.org/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:163
			if(isError) throw e;
			            ^

Error: Invariant Violation: OptimizelySubdomain.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.
    at invariant (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/invariant.js:42:15)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/ReactCompositeComponent.js:821:46)
    at [object Object].wrapper [as _renderValidatedComponent] (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/ReactPerf.js:70:21)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/ReactCompositeComponent.js:237:30)
    at [object Object].wrapper [as mountComponent] (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at [object Object].wrapper [as mountComponent] (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at [object Object].wrapper [as mountComponent] (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at [object Object].wrapper [as mountComponent] (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/ReactPerf.js:70:21)
    at /Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/ReactServerRendering.js:68:32
    at ReactServerRenderingTransaction.Mixin.perform (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/Transaction.js:134:20)
    at Object.renderToStaticMarkup (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react/lib/ReactServerRendering.js:66:24)
    at Function.<anonymous> (/Users/dascher1/davida/src/donate.mozilla.org/webpack.config.js:62:24)
    at Function.dispatchHandler (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react-router/lib/createRouter.js:381:22)
    at /Users/dascher1/davida/src/donate.mozilla.org/node_modules/react-router/lib/createRouter.js:349:29
    at /Users/dascher1/davida/src/donate.mozilla.org/node_modules/react-router/lib/Transition.js:69:9
    at Function.Transition.to (/Users/dascher1/davida/src/donate.mozilla.org/node_modules/react-router/lib/Transition.js:72:15)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "watch:js"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! donate.mozilla.org@0.0.1 watch:js: `webpack -w`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the donate.mozilla.org@0.0.1 watch:js script 'webpack -w'.
npm ERR! This is most likely a problem with the donate.mozilla.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack -w
npm ERR! You can get their info via:
npm ERR!     npm owner ls donate.mozilla.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dascher1/davida/src/donate.mozilla.org/npm-debug.log
ERROR: watch:js: None-Zero Exit(1);

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start:dev"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! donate.mozilla.org@0.0.1 start:dev: `npm-run-all --parallel build:l10njson build:exchangerates watch:js server watch:css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the donate.mozilla.org@0.0.1 start:dev script 'npm-run-all --parallel build:l10njson build:exchangerates watch:js server watch:css'.
npm ERR! This is most likely a problem with the donate.mozilla.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all --parallel build:l10njson build:exchangerates watch:js server watch:css
npm ERR! You can get their info via:
npm ERR!     npm owner ls donate.mozilla.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dascher1/davida/src/donate.mozilla.org/npm-debug.log

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! donate.mozilla.org@0.0.1 start: `node scripts/build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the donate.mozilla.org@0.0.1 start script 'node scripts/build'.
npm ERR! This is most likely a problem with the donate.mozilla.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build
npm ERR! You can get their info via:
npm ERR!     npm owner ls donate.mozilla.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dascher1/davida/src/donate.mozilla.org/npm-debug.log
dascher-29223:donate.mozilla.org dascher1$
```

**Comment by davidascher** [comment]
I had `export OPTIMIZELY_ACTIVE='no'`.  If I return it to `'yes'`, then the traceback goes away.

**Comment by ScottDowne** [comment]
Fixed in https://github.com/mozilla/donate.mozilla.org/pull/404

Weird that react considers `false` being returned as OK, but undefined is an error.

**Comment by ScottDowne** [comment]
Merged
