### ISSUE TITLE
selenium test not running locally

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate.mozilla.org#651]
Might just be my setup, so can @alicoding try it locally to see if it's me or not?

**Comment by ScottDowne** [comment]
```
undefined:1178
    vlog(2, () => this + ' scheduling notifications', this);
             ^
SyntaxError: Unexpected token )
    at goog.loadModuleFromSource_ (/home/scott/donate.mozilla.org/node_modules/selenium-webdriver/lib/goog/base.js:1123:19)
    at Object.goog.loadModule (/home/scott/donate.mozilla.org/node_modules/selenium-webdriver/lib/goog/base.js:1085:46)
    at /home/scott/donate.mozilla.org/node_modules/selenium-webdriver/lib/webdriver/promise.js:1:6
    at Object.exports.runInContext (vm.js:64:17)
    at Object.Context.closure.goog.retrieveAndExecModule_ (/home/scott/donate.mozilla.org/node_modules/selenium-webdriver/_base.js:135:8)
    at <anonymous>:1:6
    at Object.exports.runInContext (vm.js:64:17)
    at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (/home/scott/donate.mozilla.org/node_modules/selenium-webdriver/_base.js:104:12)
    at Object.goog.importScript_ (/home/scott/donate.mozilla.org/node_modules/selenium-webdriver/lib/goog/base.js:879:9)
    at Object.goog.importModule_ (/home/scott/donate.mozilla.org/node_modules/selenium-webdriver/lib/goog/base.js:900:14)

npm ERR! Linux 3.19.8-100.fc20.x86_64
npm ERR! argv "/opt/node-v0.12.7-linux-x64/bin/node" "/opt/node-v0.12.7-linux-x64/bin/npm" "run" "test:selenium"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! donate.mozilla.org@0.0.1 test:selenium: `node tests/selenium/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the donate.mozilla.org@0.0.1 test:selenium script 'node tests/selenium/start.js'.
npm ERR! This is most likely a problem with the donate.mozilla.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tests/selenium/start.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls donate.mozilla.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/scott/donate.mozilla.org/npm-debug.log

```

**Comment by ScottDowne** [comment]
I cleared node_modules and updated node to v0.12.7

**Comment by alicoding** [comment]
Node is now version 5.0.0 I think you should update again hehe but will try locally once I get home

**Comment by alicoding** [comment]
Just ran the test with no problem, but will try again after nuking my node_modules directory.

**Comment by ScottDowne** [comment]
Yeah, upgrading to 5.0.0 fixed it. It runs, finishes, but also finishes with an error.

I don't know why, but the extreme jump from 0.12.x to 5.0.0 made it feel like a different feature set, one I didn't think we were using.

**Comment by ScottDowne** [comment]
Scratch that, doesn't finish, hits an error, but I think this one is on us.

**Comment by alicoding** [comment]
I have PR to fix the other issues

**Comment by ScottDowne** [comment]
Landed and fixed.
